name: aquametrics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  camera: ^0.11.2
  flutter:
    sdk: flutter
  flutter_vision: ^2.0.0
  http: ^1.6.0
  image_picker: ^1.1.2
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.4.0+3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/aquametrics_launcher_icon.png
  remove_alpha_ios: true
  background_color_ios: "#0D5C55"

flutter:
  uses-material-design: true
  assets:
    - assets/models/
